version: '3.8'
services:
  pgvector-db:
    image: ankane/pgvector:latest
    container_name: pgvector-db
    restart: always
    environment:
      POSTGRES_DB: telusko
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0076
    ports:
      - "5432:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  pgvector-data:
